<?php
/**
 * ActivityEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Find more infos in our [API documentation](https://www.kimai.org/documentation/rest-api.html).
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ActivityEntityTest Class Doc Comment
 *
 * @category    Class
 * @description ActivityEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActivityEntityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ActivityEntity"
     */
    public function testActivityEntity()
    {
    }

    /**
     * Test attribute "parentTitle"
     */
    public function testPropertyParentTitle()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "colorSafe"
     */
    public function testPropertyColorSafe()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "visible"
     */
    public function testPropertyVisible()
    {
    }

    /**
     * Test attribute "billable"
     */
    public function testPropertyBillable()
    {
    }

    /**
     * Test attribute "metaFields"
     */
    public function testPropertyMetaFields()
    {
    }

    /**
     * Test attribute "teams"
     */
    public function testPropertyTeams()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "budget"
     */
    public function testPropertyBudget()
    {
    }

    /**
     * Test attribute "timeBudget"
     */
    public function testPropertyTimeBudget()
    {
    }

    /**
     * Test attribute "budgetType"
     */
    public function testPropertyBudgetType()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }
}
