<?php
/**
 * TimesheetConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Find more infos in our [API documentation](https://www.kimai.org/documentation/rest-api.html).
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * TimesheetConfigTest Class Doc Comment
 *
 * @category    Class
 * @description TimesheetConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimesheetConfigTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimesheetConfig"
     */
    public function testTimesheetConfig()
    {
    }

    /**
     * Test attribute "trackingMode"
     */
    public function testPropertyTrackingMode()
    {
    }

    /**
     * Test attribute "defaultBeginTime"
     */
    public function testPropertyDefaultBeginTime()
    {
    }

    /**
     * Test attribute "activeEntriesHardLimit"
     */
    public function testPropertyActiveEntriesHardLimit()
    {
    }

    /**
     * Test attribute "isAllowFutureTimes"
     */
    public function testPropertyIsAllowFutureTimes()
    {
    }

    /**
     * Test attribute "isAllowOverlapping"
     */
    public function testPropertyIsAllowOverlapping()
    {
    }
}
