<?php
/**
 * CustomerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Find more infos in our [API documentation](https://www.kimai.org/documentation/rest-api.html).
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteCustomer
     *
     * Delete customer.
     *
     */
    public function testDeleteCustomer()
    {
    }

    /**
     * Test case for deleteCustomerRate
     *
     * Delete rate for customer.
     *
     */
    public function testDeleteCustomerRate()
    {
    }

    /**
     * Test case for getCustomer
     *
     * Fetch customer.
     *
     */
    public function testGetCustomer()
    {
    }

    /**
     * Test case for getCustomerRates
     *
     * Fetch rates for customer.
     *
     */
    public function testGetCustomerRates()
    {
    }

    /**
     * Test case for getCustomers
     *
     * Fetch customers.
     *
     */
    public function testGetCustomers()
    {
    }

    /**
     * Test case for patchAppApiCustomerMeta
     *
     * Update customer custom-field.
     *
     */
    public function testPatchAppApiCustomerMeta()
    {
    }

    /**
     * Test case for patchCustomer
     *
     * Update customer.
     *
     */
    public function testPatchCustomer()
    {
    }

    /**
     * Test case for postCustomer
     *
     * Create customer.
     *
     */
    public function testPostCustomer()
    {
    }

    /**
     * Test case for postCustomerRate
     *
     * Add rate for customer.
     *
     */
    public function testPostCustomerRate()
    {
    }
}
