<?php
/**
 * ProjectApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Find more infos in our [API documentation](https://www.kimai.org/documentation/rest-api.html).
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteProject
     *
     * Delete project.
     *
     */
    public function testDeleteProject()
    {
    }

    /**
     * Test case for deleteProjectRate
     *
     * Delete rate for project.
     *
     */
    public function testDeleteProjectRate()
    {
    }

    /**
     * Test case for getProject
     *
     * Fetch project.
     *
     */
    public function testGetProject()
    {
    }

    /**
     * Test case for getProjectRates
     *
     * Fetch rates for project.
     *
     */
    public function testGetProjectRates()
    {
    }

    /**
     * Test case for getProjects
     *
     * Fetch projects.
     *
     */
    public function testGetProjects()
    {
    }

    /**
     * Test case for patchAppApiProjectMeta
     *
     * Update project custom-field.
     *
     */
    public function testPatchAppApiProjectMeta()
    {
    }

    /**
     * Test case for patchProject
     *
     * Update project.
     *
     */
    public function testPatchProject()
    {
    }

    /**
     * Test case for postProject
     *
     * Create project.
     *
     */
    public function testPostProject()
    {
    }

    /**
     * Test case for postProjectRate
     *
     * Add rate for project.
     *
     */
    public function testPostProjectRate()
    {
    }
}
