<?php
/**
 * TeamApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Find more infos in our [API documentation](https://www.kimai.org/documentation/rest-api.html).
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeamApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteTeam
     *
     * Delete team.
     *
     */
    public function testDeleteTeam()
    {
    }

    /**
     * Test case for deleteTeamActivity
     *
     * Revoke activity access.
     *
     */
    public function testDeleteTeamActivity()
    {
    }

    /**
     * Test case for deleteTeamCustomer
     *
     * Revoke customer access.
     *
     */
    public function testDeleteTeamCustomer()
    {
    }

    /**
     * Test case for deleteTeamMember
     *
     * Remove team member.
     *
     */
    public function testDeleteTeamMember()
    {
    }

    /**
     * Test case for deleteTeamProject
     *
     * Revoke project access.
     *
     */
    public function testDeleteTeamProject()
    {
    }

    /**
     * Test case for getTeam
     *
     * Fetch team.
     *
     */
    public function testGetTeam()
    {
    }

    /**
     * Test case for getTeams
     *
     * Fetch teams.
     *
     */
    public function testGetTeams()
    {
    }

    /**
     * Test case for patchTeam
     *
     * Update team.
     *
     */
    public function testPatchTeam()
    {
    }

    /**
     * Test case for postTeam
     *
     * Create team.
     *
     */
    public function testPostTeam()
    {
    }

    /**
     * Test case for postTeamActivity
     *
     * Grant activity access.
     *
     */
    public function testPostTeamActivity()
    {
    }

    /**
     * Test case for postTeamCustomer
     *
     * Grant customer access.
     *
     */
    public function testPostTeamCustomer()
    {
    }

    /**
     * Test case for postTeamMember
     *
     * Add team member.
     *
     */
    public function testPostTeamMember()
    {
    }

    /**
     * Test case for postTeamProject
     *
     * Grant project access.
     *
     */
    public function testPostTeamProject()
    {
    }
}
