<?php
/**
 * TimesheetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Find more infos in our [API documentation](https://www.kimai.org/documentation/rest-api.html).
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TimesheetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TimesheetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteTimesheet
     *
     * Delete timesheet.
     *
     */
    public function testDeleteTimesheet()
    {
    }

    /**
     * Test case for getActiveTimesheet
     *
     * Fetch active timesheets.
     *
     */
    public function testGetActiveTimesheet()
    {
    }

    /**
     * Test case for getRecentTimesheet
     *
     * Fetch recent user activities.
     *
     */
    public function testGetRecentTimesheet()
    {
    }

    /**
     * Test case for getRestartTimesheetGet
     *
     * Restart timesheet.
     *
     */
    public function testGetRestartTimesheetGet()
    {
    }

    /**
     * Test case for getStopTimesheetGet
     *
     * Stop active timesheet.
     *
     */
    public function testGetStopTimesheetGet()
    {
    }

    /**
     * Test case for getTimesheet
     *
     * Fetch timesheet.
     *
     */
    public function testGetTimesheet()
    {
    }

    /**
     * Test case for getTimesheets
     *
     * Fetch timesheets.
     *
     */
    public function testGetTimesheets()
    {
    }

    /**
     * Test case for patchAppApiTimesheetMeta
     *
     * Update timesheet custom-field.
     *
     */
    public function testPatchAppApiTimesheetMeta()
    {
    }

    /**
     * Test case for patchDuplicateTimesheet
     *
     * Duplicate timesheet.
     *
     */
    public function testPatchDuplicateTimesheet()
    {
    }

    /**
     * Test case for patchExportTimesheet
     *
     * Toggle timesheet export state.
     *
     */
    public function testPatchExportTimesheet()
    {
    }

    /**
     * Test case for patchRestartTimesheet
     *
     * Restart timesheet.
     *
     */
    public function testPatchRestartTimesheet()
    {
    }

    /**
     * Test case for patchStopTimesheet
     *
     * Stop active timesheet.
     *
     */
    public function testPatchStopTimesheet()
    {
    }

    /**
     * Test case for patchTimesheet
     *
     * Update timesheet.
     *
     */
    public function testPatchTimesheet()
    {
    }

    /**
     * Test case for postTimesheet
     *
     * Create timesheet.
     *
     */
    public function testPostTimesheet()
    {
    }
}
